version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.1
        environment:
          MIX_ENV: test

    working_directory: ~/data

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
